public class ApexIntro1 {
//public is an access modifier.An access modifier defines the visibility of an apex class A class can have global(acroos org) or public(only to 1 naespace0 access modifiers but never can be private
//A class can contain variable definition and method definition

//methods inside the class contain business logic and executed once the class is instantiated.creating an in memory representation

Public void Method()
{

}
}